services:
  comfyui:
    image: comfyui-rocm-7.1.1
    container_name: comfyui-rocm-7
    ports:
      - 8188:8188
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp=unconfined
    group_add:
      - video
    volumes:
      - ~/.comfyui/user:/comfyui/user:rw
      - ~/.comfyui/models:/comfyui/models:rw
      - ~/.comfyui/output:/comfyui/output:rw
      - ~/.comfyui/custom_nodes:/comfyui/custom_nodes:rw
    stdin_open: true
    tty: true
    restart: always
