services:
  comfyui:
    image: comfyui-rocm-7.2
    container_name: comfyui-rocm-7
    user: "${USER_UID}:${USER_GID}"
    ports:
      - 8188:8188
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp=unconfined
    group_add:
      - video
      - render
    volumes:
      - ~/.comfyui/user:/app/ComfyUI/user:rw
      - ~/.comfyui/models:/app/ComfyUI/models:rw
      - ~/.comfyui/output:/app/ComfyUI/output:rw
      - ~/.comfyui/input:/app/ComfyUI/input:rw
      - ~/.comfyui/custom_nodes:/app/ComfyUI/custom_nodes:rw
    stdin_open: true
    tty: true
    restart: always
